"""add_satellites

Revision ID: 009
Revises: 008
Create Date: 2025-08-12 12:34:15.912769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: str | None = "008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("orbit_id", sa.Integer(), nullable=False),
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column("paired", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "capabilities",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("last_seen_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(paired = false AND cardinality(capabilities) = 0) OR "
            "(paired = true AND cardinality(capabilities) >= 1)",
            name="satellite_pairing_capabilities_check",
        ),
        sa.ForeignKeyConstraint(["orbit_id"], ["orbits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
    )
    op.create_table(
        "satellite_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("orbit_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column(
            "scheduled_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["orbit_id"], ["orbits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["satellite_id"], ["satellites.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("satellite_queue")
    op.drop_table("satellites")
    # ### end Alembic commands ###
